### ISSUE TITLE
on-demand usage via cargo command/wrapper

### ISSUE THREAD

**Issue by arcnmx** [athre0z/color-backtrace#12]
Being able to use this crate to aid in debugging without adding it to every project or when needed seems like it would be a nice frictionless way to get better backtraces, and helps with things like #3.

[I've started sketching out a cargo subcommand for this](https://github.com/arcnmx/cargo-panic), and am considering an alias or wrapper that would make `RUST_BACKTRACE=color` a more transparent/automatic thing. Though it seems to work well enough, the interaction with cargo and the linker is somewhat fragile with this approach. Is there any interest in offering or maintaining something similar or would it be best to keep this separate?

**Comment by athre0z** [comment]
I think that's an interesting idea! 

I think keeping it separate will be better & it is beyond the scope of this lib. Keeping it external also allows users to choose between different competing implementations of the same lib without being somewhat weird (e.g. `pretty_backtrace`) and adding more useful debug libs later without introducing bloat for people who just want pretty backtraces.

If you decide to continue your efforts and have it at a point where you consider it ready for general use, let me know & I'll be happy to add a link to your project into this lib's README!
