### ISSUE TITLE
Coloring make text invisible with white background.

### ISSUE THREAD

**Issue by s3bk** [athre0z/color-backtrace#13]
Problem: https://paste.rs/JkB.png
Terminal: Konsole with "black on white" theme

A solution would be to use "default color" + bold.

**Comment by athre0z** [comment]
Thank you for reporting this! I never use light term themes, so I didn't think of this. Using bold is an excellent suggestion, it looks even better on dark themes than the previous bright white and works fine with light themes as well.

**Comment by s3bk** [comment]
Thanks! (And I can't spell)
