### ISSUE TITLE
Coloring is broken in IntelliJ since "Only colorize output when printing to a tty"

### ISSUE THREAD

**Issue by ArekPiekarz** [athre0z/color-backtrace#14]
Since version 0.2.0 coloring of backtraces doesn't work in IntelliJ with Rust plugin. The backtraces are printed as normal text, for me as white on gray background.

I narrowed down the bug to commit ec5803ad5ff9e60888f0dfdf6492b4c2fcadd373 - "Only colorize output when printing to a tty". I don't know what IntelliJ does under the hood, but it seems it redirects output to a file? Maybe the plugin's source code holds the answer - https://github.com/intellij-rust/intellij-rust

Steps to reproduce:
1. Assuming you have IntelliJ with Rust plugin, create new project with File -> New -> Project.
2. Choose Rust template, click Next, name the project, click Finish.
3. Use these files:
src/main.rs:
```
fn main() {
    color_backtrace::install();
    panic!("I'm panicking");
}
```
Cargo.toml
```
[package]
name = "color-backtrace-test"
version = "0.1.0"
authors = ["John Smith"]
edition = "2018"

[dependencies]
#color-backtrace = "0.1.3" # works
#color-backtrace = "0.2.0" # doesn't work
#color-backtrace = {git = "https://github.com/athre0z/color-backtrace", rev = "0c72936b02ad9f78fe7df87d9364bb3eeffcce67"} # works
color-backtrace = {git = "https://github.com/athre0z/color-backtrace", rev = "ec5803ad5ff9e60888f0dfdf6492b4c2fcadd373"} # doesn't work
```
4. On the right click "Add configuration".
5. In the dialog on the left click "+" -> Cargo Command
6. The "Command" field should say "run", you can fill the "Name" field as "cargo run", click Ok.
7. Run the newly added command by the "Run" button right from it (or hit Shift+F10 by default).

**Comment by athre0z** [comment]
Well, I guess this is something that should probably instead be reported to the IJ plugin authors. The Python "plugin" (PyCharm) has a run setting for emulating a terminal when running, the IJ Rust people should probably implement something comparable.

For the time being, [I just added an example](https://github.com/athre0z/color-backtrace/commit/62b00dcf8e55a90e0b4e990ea918af790c480a78
) on how to force color printing even when not printing to a tty here.

**Comment by athre0z** [comment]
Since this is now implemented in IJ Rust and they tested it with color-backtrace, I'll assume this is resolved now. Feel free to reopen in case of any further issues!
