### ISSUE TITLE
`color_backtrace::install()` panics if `TERM` environment variable is not set

### ISSUE THREAD

**Issue by pyrrho** [athre0z/color-backtrace#15]
More specifically, `color_backtrace::Settings::default()` may panic on `let term = term::stderr().unwrap();`. `term` uses a number of heuristics to determine how to populate it's `TermInfo` struct, and the first and simplest is reading the `TERM` env var, and branching based on that. When `TERM` is unset, `term::stderr()` will return `None`.

I hit this condition in a [Buildkite](https://buildkite.com/) CI system, which (I believe) uses `execve` to control the execution context -- most notably the build agent's environment. As it doesn't set `TERM`, my automatic tests started exploding as soon as I updated from `color_backtrace` 1.3 to 2.0.

My work-around is currently to check `if std::env::var("TERM").is_ok()` before calling `color_backtrace::install()` but that seems to be a rather brittle and lack-luster solution. My first instinct would be to change the signature of `install()` to something like `pub fn install() -> Result<(), ???>` but I'm 1) not familiar with how you're managing Error types in this library, and 2) not terribly comfortable with the idea of editing some of this library's most visible API without having a chat about it first.

Let me know if you have any questions about my issue, or if I might be able to help resolve it in the library.

**Comment by athre0z** [comment]
Thank you for the detailed bug report! I just pushed 5808001f3ff13ae164e4ee0768ef34e137b0609f, falling back to non-colorized stderr printing if `term` is unable to acquire stderr. Please let me know if this resolves your issue! :)

**Comment by pyrrho** [comment]
Thanks for the fast turn-around! Seems like a good solution to me, I'm pretty sure it'll work just fine for my CI.

I think you're good to close this issue out!

**Comment by athre0z** [comment]
Great! I just released v0.2.1 with this fix included.
