### ISSUE TITLE
Document SNAFU backtrace printing integration

### ISSUE THREAD

**Issue by yaahc** [athre0z/color-backtrace#19]
~~I'm currently in the process of porting a project from `failure` to `SNAFU` to try it out and I'd like to be able to use color-backtrace with SNAFU backtraces. They also use an opaque wrapper type same as failure, though theirs is a much simpler wrapper, just a NewType, so doing the hacky failure style integration should be trivial.~~

~~I would however like to communicate with the SNAFU devs and the failure devs and the guy who works on std that I talked to last time who had plans for getting backtraces into the `std::error::Error` API and make sure everyone is on the same page so all the integration eventually gets done the right way.~~

Since it seems that SNAFU already has a way to extract the inner `backtrace::Backtrace`, I propose that `color-backtrace`'s README should be updated to document this fact, along side the existing notes on how to integrate with `failure`.

I'm planning on getting to this **soonish**

**Comment by ArekPiekarz** [comment]
Snafu has an optional feature "backtrace-crate" that enables converting its wrapped backtrace into backtrace::Backtrace, which is supported by color-backtrace - https://github.com/shepmaster/snafu/blob/master/Cargo.toml#L31

**Comment by yaahc** [comment]
Boom! problem solved for now. Ty @ArekPiekarz

**Comment by yaahc** [comment]
Actually, let me change this issue, we should probably document how to use `color-backtrace` with `SNAFU` in the README.

**Comment by athre0z** [comment]
Sounds good -- I'll be happy to review a PR!

**Comment by yaahc** [comment]
I think this is no longer necessary with the `format_to_string` support that's been added.
