### ISSUE TITLE
Colorful backtrace for Failure & co

### ISSUE THREAD

**Issue by omarabid** [athre0z/color-backtrace#23]
So I'm trying to color the backtrace while having my own `Error` type. Here is the thing, I want to use the rust way of returning errors. All errors propagate to the main() function and are returned there.

```
fn main() -> Result<()> {
... code goes here
}
```

Is there a way to catch the error/backtrace from the main() function? How do you integrate with color-backtrace?

**Comment by athre0z** [comment]
I don't think so -- you would have to "catch" the errors in your top level function (=main) and call `color_backtrace::failure::print_backtrace` on them. I don't really think this is an issue though, I'd say that the ability to return `Result<T, E>` from main is more of a convenience feature than something that has to be done to write idiomatic Rust code.
