### ISSUE TITLE
Provide custom frame filtering option

### ISSUE THREAD

**Issue by winstonewert** [athre0z/color-backtrace#25]
I'm using color-backtrace along with rayon.

The trouble is that rayon produces absurdly long stack traces. I'm looking at one with 150 frames right now.

These long stack traces push my interesting stack traces way way up my scroll buffer.

I'd like to filter out the rayon stack frames. Its probably too much to task for color-backtrace to do it for me, but it'd be nice if I had the option to provide custom filtering logic.

**Comment by athre0z** [comment]
I started working on supporting that a while ago, the progress is on the [`features/custom-filter` branch](https://github.com/athre0z/color-backtrace/tree/feature/custom-filters) -- feel free to check it out! Currently, you would have to create a struct that implements the `FrameFilter` trait, adding your checks and then delegate to the `DefaultFilter`. The filter can then be set via `Settings::filter`.

I feel like this interface is a bit too clunky, I'll probably replace it with something along the lines of just adding a callback, but it should work.

**Comment by winstonewert** [comment]
I finally came back and tried this out.

Firstly, it didn't work because the Frame struct doesn't have public fields or useful public methods to get at the information. So my filter couldn't do anything besides call DefaultFilter. I resolved that by forking and adding `pub` to the struct fields.

Agreed that the interface probably makes more sense as a providing a simple function, but its not too bad since its something I only need to setup once.

More problematic is that I can only look at one frame at a time.  For example, in the thread startup code I see this in the middle of this:

     <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

Evidently, the thread startup involves invoking a boxed function. I don't want to see this in my backtrace, but its not like boxed function invoking is inherently uninteresting runtime code. 

It would make more sense to be able to identify:

- This thread begins with clone and start_thread
- It also contains __rust_begin_short_backtrace
- Remove everything between those two:

Which of course cannot be done looking one frame at a time.

**Comment by winstonewert** [comment]
On the other hand:

If color_backtrace knew how to remove the start of the thread backtrace, all I actually need is the ability to add prefixes to the lists in the already existing filtering logic.

**Comment by yaahc** [comment]
Looking at https://github.com/athre0z/color-backtrace/compare/feature/custom-filters I would prefer an option that preserves the existing filers and simply adds some new ones over one that lets me override all the logic, because for my case at least I would end up just copying all of the existing panic logic from the upstream anyways, but now if don't get to benefit from them because I've effectively vendored the provided filtering.

**Comment by athre0z** [comment]
Yeah, I feel like my first attempt at this on `features/custom-filter` is both severely over-engineered and limiting -- let's abandon it. On the other hand, only providing string filtering, I find @yaahc's PR a bit too limiting. I've had some people talk to me privately that had expressed an interest in being able to execute custom code for the filtering.

Perhaps we can find a middle ground here:
- Don't touch dependency code detection for now and leave this for later
- Expose `Frame` and it's fields as `pub`
  - Methods remain private for now
  - Add `n` field containing the frame's index (purpose will become apparent later)
- For frame filtering, have a chain of filtering callbacks `type FilterCallback = dyn FnMut(frames: Vec<&Frame>) -> Vec<&Frame>`
- Refactor & merge `is_post_panic_code` and `is_runtime_init_code` to match the filter callback signature from above, move it out of `Frame`, make it public as `default_frame_filter`.
- Add a `Vec<Box<FilterCallback>>` to `PanicPrinter` (`Settings` on master), initialize it with `vec![box is_post_panic_code]`
- Add accessors `clear_frame_filters` and `add_frame_filter` to `PanicPrinter`
- The printing code would then invoke each filter in the chain successively, each filter receiving the output of the previous filter
- Using the new `n` index field in the frame, the frame printing code will detect where frames have been elided and print a neat unicode `⁞`, as well as perhaps how many frames have been hidden
  - Happy to hear about any other nice ways of representing omitted content, other unicode glyphs etc

So @yaahc for your simple string filter, you'd pretty much have to write

```rust
PrettyPrinter::new()
    .add_frame_filter(|frames| {
        frames
            .into_iter()
            .filter(|x| x.name != "blablablabla")
            .collect()
    })
    .install(default_output_stream());
```

If you feel this is still too much, we could perhaps add a third accessor `add_string_frame_filter` that just adds this closure above with the user provided string.

**Comment by yaahc** [comment]
This sounds perfect, did you want me to go ahead and open a PR to implement this?

**Comment by athre0z** [comment]
Well, I didn't expect you to do that work and planned waiting for a review of my design and then hacking this together tomorrow (it's 01:27 in the morning here in Germany), but if you are particularly eager to get this done ASAP, you're absolutely welcome to PR it. :)

**Comment by yaahc** [comment]
I think ill probably end up doing it for fun, tho i'm not gonna put too much effort into the unicode bit because I dont know exactly how you want it and I feel like you've already proven yourself to be quite good at creating nice formatting. So hopefully you'll have a nice branch you can pull tomorrow, tidy up, and merge.
