### ISSUE TITLE
Usage with tests

### ISSUE THREAD

**Issue by jannikkeye** [athre0z/color-backtrace#3]
Is it possible to somehow use this for panics in tests? It may help me with debugging.

**Comment by athre0z** [comment]
Unfortunately, there is no support for running initialization code before tests in Rust, so you'll have to manually put the install call into each test for now / write a macro.

See this issue for some discussion about adding such test initialization support: https://github.com/rust-lang/rfcs/issues/1664

**Comment by jannikkeye** [comment]
Thank you for the timely reply. Would such a macro be in the context of your lib or should I roll my own per project?

**Comment by athre0z** [comment]
GIven that this would likely have to be a proc macro in order to allow for the ergonomic attribute style syntax which must live in a second crate, I think this is unfortunately out of scope for this lib.

**Comment by athre0z** [comment]
A different approach would be to use the [`ctor`](https://docs.rs/ctor/0.1.9/ctor/attr.ctor.html) crate to add an init function that is called before main to call the install function. I think this might be your best option.

In case you were wondering whether it wouldn't be nice to do that in this lib: unfortunately, it wouldn't work. Modules that aren't referenced by the main application explicitly in some way aren't linked into the final binary, no matter if they have `#[used]` or `#[ctor]` items.

**Comment by jannikkeye** [comment]
Fair enough, thanks for the explanation and link! Great job on the library!
