### ISSUE TITLE
Use `RUST_LIB_BACKTRACE` env variable for non panic backtrace verbosity

### ISSUE THREAD

**Issue by yaahc** [athre0z/color-backtrace#30]
With the upstream inclusion of Backtrace in std the ecosystem seems to be moving towards using `RUST_BACKTRACE` for panic based backtraces and `RUST_LIB_BACKTRACE` for `std::backtrace::Backtrace`.

I think this will take like 5 minutes to do so I'm gonna open a PR for this one too, in my patched version i just swapped it completely but after thinking abuot it for a sec I think its important to separate the verbosity the same way std does.

**Comment by bjorn3** [comment]
> RUST**C**_LIB_BACKTRACE

I think you meant `RUST_LIB_BACKTRACE`.
