### ISSUE TITLE
add support for deserializing and printing `std::backtrace::Backtrace`

### ISSUE THREAD

**Issue by yaahc** [athre0z/color-backtrace#35]
The nightly std::backtrace::Backtrace has a debug format that is relatively easy to parse. There are plans to eventually add a frame iterator api to backtrace similar to `backtrace-rs`'s Backtrace but it seems rather far off. Until then I think it makes sense to write a deserializer for the `Debug` format of backtrace, which should hopefully be pretty stable, and use that to build the `Frame` objects used internally to print the backtrace.

**Comment by bjorn3** [comment]
> which should hopefully be pretty stable

`Debug` implementations are **not** stable. Don't parse it! https://github.com/rust-lang/rust/pull/59076 caused a lot of test breakage, because people depended on the exact debug formatting of structs in pretty print mode.

cc https://github.com/rust-lang/rust/issues/62794.

**Comment by ArekPiekarz** [comment]
It looks like it's a duplicate of https://github.com/athre0z/color-backtrace/issues/24. But it means that more people care about solving this problem.

**Comment by yaahc** [comment]
aah, fair enough, ill close this and add my comments to the other issue.
