### ISSUE TITLE
bump backtrace-rs dependency to newest version

### ISSUE THREAD

**Issue by yaahc** [athre0z/color-backtrace#40]
related to https://github.com/rust-lang/backtrace-rs/issues/334

theres a bug in `backtrace:0.3.46` that causes panics on arm (or at least raspberry pi) that has been fixed in the newest version.

fixes https://github.com/yaahc/color-eyre/issues/7

**Comment by bjorn3** [comment]
There is no need to bump the dependency in this crate. This crate depends on backtrace `0.3`, which means that the current `0.3.48` version is allowed. All you need to do is run `cargo update` to update `Cargo.lock` of the program you are compiling.

https://github.com/athre0z/color-backtrace/blob/85b46b178d3a512d574bec587e1b8ad8c7882f56/Cargo.toml#L32

https://github.com/rust-lang/backtrace-rs/blob/02bc46fa34beac05e982a109db51fb5d376c287f/Cargo.toml#L3
