### ISSUE TITLE
Consider making `Frame::is_dependency_code` public?

### ISSUE THREAD

**Issue by WindSoilder** [athre0z/color-backtrace#48]
Hi, thanks for the awesome crate, I love it really much.
One issue for me is default backtrace is sometimes too verbosing to me..

And I found `Frame` provides `is_dependency_code` method to make output to have different colors.

I think it would be good to have a way to filter frames by `is_dependency_code` too, it will make backtrace much simpler because I don't need to see something like `tokio`'s backtrace

Currently I can't write something like this:
```rust
use color_backtrace::{default_output_stream, BacktracePrinter};
let printer = BacktracePrinter::new();
# it failed because `is_dependency_code` is a private method.
let printer =
     printer.add_frame_filter(Box::new(|frames| frames.retain(|x| !x.is_dependency_code)));
let mut stream = default_output_stream();
let tb = backtrace::Backtrace::new();
let _ = printer.print_trace(&tb, &mut stream);
```

What do you think?

**Comment by athre0z** [comment]
Hey! Yep, that sounds reasonable. We should probably expose all the `is_xyz` functions.
