### ISSUE TITLE
hold the stdout lock to detangle multithreaded panics

### ISSUE THREAD

**Issue by spacejam** [athre0z/color-backtrace#7]
my naive assumption is that it might not be so much work to take out the stdout lock once before iterating over each item in a backtrace and printing them out as a consistent block.

I cause a ton of concurrent panics where hundreds of lines can sometimes fill the space between the initial panic message and parts of the relevant file information. By taking out the stdout lock just once and holding it until the entire backtrace is completed, I assume it would make these error messages much more consistent.

I'd be happy to investigate farther if you think this would be helpful! Let me know :]

**Comment by spacejam** [comment]
whoops, I see this is already implemented, thanks in the past xD

**Comment by athre0z** [comment]
Haha, no problem! :D
